### ISSUE TITLE
Couldn't generate png image

### ISSUE THREAD

**Issue by rubanraj54** [dmester/jdenticon-php#2]
I am trying to generate png images, but failing with the following exception.

```
ImagickException
unable to open file `/tmp/magick-64T_RFaCmhklN': No such file or directory @ error/constitute.c/ReadImage/544


in ImagickRenderer.php line 97
--
at Imagick->readimageblob('<?xml version="1.0" encoding="UTF-8" ?><svg xmlns="http://www.w3.org/2000/svg" width="100.00" height="100.00" viewBox="0 0 100.00 100.00" preserveAspectRatio="xMidYMid meet"><rect fill="#ffffff" fill-opacity="1.00" x="0" y="0" width="100.00" height="100.00"/><path fill="#545454" d="M32.50 18.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M53.50 18.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M53.50 81.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M32.50 81.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M11.50 39.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M74.50 39.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M74.50 60.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0M11.50 60.50a7.00,7.00 0 1,1 14.00,0a7.00,7.00 0 1,1 -14.00,0"/><path fill="#d1757a" d="M8.00 18.50L18.50 8.00L29.00 18.50L18.50 29.00ZM81.50 8.00L92.00 18.50L81.50 29.00L71.00 18.50ZM92.00 81.50L81.50 92.00L71.00 81.50L81.50 71.00ZM18.50 92.00L8.00 81.50L18.50 71.00L29.00 81.50ZM29.00 29.00L50.00 29.00L50.00 50.00L29.00 50.00ZM36.56 42.02a5.46,5.46 0 1,0 10.92,0a5.46,5.46 0 1,0 -10.92,0M71.00 29.00L71.00 50.00L50.00 50.00L50.00 29.00ZM52.52 42.02a5.46,5.46 0 1,0 10.92,0a5.46,5.46 0 1,0 -10.92,0M71.00 71.00L50.00 71.00L50.00 50.00L71.00 50.00ZM52.52 57.98a5.46,5.46 0 1,0 10.92,0a5.46,5.46 0 1,0 -10.92,0M29.00 71.00L29.00 50.00L50.00 50.00L50.00 71.00ZM36.56 57.98a5.46,5.46 0 1,0 10.92,0a5.46,5.46 0 1,0 -10.92,0"/></svg>')in ImagickRenderer.php line 97

```

But i can able to generate svg images. Any idea how to resolve this issue would be helpful?

**Comment by dmester** [comment]
Jdenticon is able to generate PNG icons in two ways, either by using an embedded PNG encoder, or by creating an SVG icon converted to PNG using ImageMagick. If ImageMagick is installed it will use ImageMagick, otherwise the embedded PNG encoder is used.

In your case ImageMagick seems to be used. The error could be thrown if your server lacks the libmagickcore*-extra library, which provides SVG support for ImageMagick. See this Stack Overflow response:
https://stackoverflow.com/a/33287686

**Possible solution**
Install the appropriate `libmagickcore*-extra` library. Choose the library matching the version of the installed ImageMagick.

Also which PHP version do you use? If using PHP 7 another solution would be to force Jdenticon to use the embedded PNG encoder. However that would require a new option in the Jdenticon API for controlling which PNG encoder that should be used.

**Comment by dmester** [comment]
There is a new release that should solve this issue. Please try to update Jdenticon to version 0.10.0 and try again. No other modifications to your code or setup are required. `libmagickcore-extra` is no longer required.

If you still have problems, please try to set `enableImageMagick` to `false`. E.g.:
```php
<?php
include_once("vendor/autoload.php");

$icon = new \Jdenticon\Identicon(array(
    'size' => 100,
    'value' => 'testicon',
    'enableImageMagick' => false
));
$icon->displayImage('png');
```

**Comment by rubanraj54** [comment]
Thank you very much for the quick response. The patch solved my issue and now it can generate png file and so closing the issue.
